spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:h2:mem:exchangeDB;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080


